DEF_BINARY( 9,  CALL,   "кил кунта")
DEF_BINARY(10,  PLUS,   "+")
DEF_BINARY(11,  MINUS,  "-")
DEF_BINARY(12,  MUL,    "*")
DEF_BINARY(13,  DIV,    "/")
DEF_BINARY(14,  POW,    "^")
DEF_BINARY(15,  EQUAL,  "==")
DEF_BINARY(16,  GREAT,  ">")
DEF_BINARY(17,  LESS,   "<")
DEF_BINARY(18,  GEQ,    ">=")
DEF_BINARY(19,  LEQ,    "<=")
DEF_BINARY(20,  NEQ,    "!=")
DEF_BINARY(21, ASSIGN,  ":=")