DEF_KEY(22, IF,     "enchen te")
DEF_KEY(23, WHILE,  "xallexe")
DEF_KEY(25, INT,    "layax")
DEF_KEY(26, FLOAT,  "xullka")
DEF_KEY(27, STRING, "stringsem")
DEF_KEY(28, ELSE,   "uraxla")
DEF_KEY(28, DEF,    "kupasta yashki mene pelternine anlantarsa parap")