DEF_UNARY(0, SIN,   "синус")            
DEF_UNARY(1, COS,   "косинус")          
DEF_UNARY(2, SQRT,  "тымар")            
DEF_UNARY(3, LN,    "логарифм")  
DEF_UNARY(4, NOT,   "щук")
DEF_UNARY(5, OUT,   "хисеп пичетле")
DEF_UNARY(6, OUT_S, "самах пичетле")
DEF_UNARY(7, IN,    "вула")
DEF_UNARY(8, RET,   "пар")   